name: Bad CI/CD file

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Install dependencies
      run: npm install

      - name: Run tests
      run: npm test

      - name: Build project
      run: npm run build

      - name: Deploying
      run: ./deploy.sh
