name: CI/CD with Secrets

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
        url: https://vault.mycompany.com:8200
        token: ${{ secrets.VAULT_TOKEN }}
        caCertificate: ${{ secrets.VAULT_CA_CERT }}
        secrets: |
          secret/data/ci/keys firstKey | FIRST_SECRET_KEY ;
          secret/data/ci/keys secondKey | SECOND_SECRET_KEY ;

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest --key1 ${{ steps.import-secrets.outputs.FIRST_SECRET_KEY }} --key2 ${{ steps.import-secrets.outputs.SECOND_SECRET_KEY }}
