name: Bad CI/CD file

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Install dependencies
      run: npm install

      - name: Run tests
      run: npm test

      - name: Deploying
      run: ./deploy.sh
